### PR TITLE
A1-PR

### PR DESCRIPTION
**Pull request by cyberchai**
Number of docked bikes now visible on the page for each station. Attempted but not finished making the descending station list with the click of a button (right now they are two separate components), and some of the bike list view is set up but not finished.

### CODE REVIEW

**Comment by cyberchai** [comment]
A4 Pull Request

**Comment by cyberchai** [comment]
Instructions
Make sure you have relevant gems installed: asdf, bycryt (version 3.1.11) - this takes care of the password security, and devise(version 4.9.11).
Eventually you will need to have additional gems for our payment system and such, but we will specify this in our later submission.

Run these commands:
bundle install 
Then, set your database password in database.yml or create an .env file.
Next, run these commands:
import stations with the following commands:
rake db:import_station["notes/station-data.csv"] 
import bike data with the following commands:
rake db:import_station["notes/bike-data.csv"]
rails db:migrate
This last command will connect you to the database so you can access our site for now:
rails s

Functionality
We have a basic login and sign in page. Our user information gets saved to our database. We also have a menu bar with various options: Sign-in, Log-in, Stations, and Profile.
Stations lets you view a list of stations. On the stations page, you can then view the bike fleet by clicking ‘View bike fleet.’ At this stage, you can select a bike to pay to rent out! When you click on a bike, you will be taken to a payment calculation page where you can select the number of hours you want to rent a bike for. Next this, you will be taken to a payment page. Our current submission version has the payment page linked to the general ‘View bike fleet’ page, but this is not permanently at this position.
The Profile page will eventually let users view their own Bikesia user information, such as miles traveled and how much money they have in their account, as well as rewards or other services or marketing strategies we may implement.

Recommended walk-through of features
Start at sign-in. Create your own account! It can be a dummy account, such as [test2@test.com](mailto:test2@test.com) and password: test123456789.
Logout and log back in if you want to see this working! But it’ll automatically keep you signed in with the account you initially created if you haven’t logged out.
Check out your profile! There isn’t much there yet.
Next, check out what Western Mass Bikesia stations are around for you to start your journey at.
Pick a bike to use that is docked and available at your selected station.
Rent it! Click payment, (select your hours), fill out your payment information, and start riding!
We will eventually add functions to return the bike as well! And that’s our basic functionality with our initial prototype!

**Comment by emmatschu** [comment]
Pull req:
Instructions:
Make sure you have relevant gems installed: asdf, bcrypt (version 3.1.11), geocoder, and mapkick, and devise(version 4.9.11). A full list of necessary gems can be found in our Gemfile document inside of our Bikesia project folder.

Run these commands:
bundle install 
Then, set your database password in database.yml or create an .env file.

Next, run these commands:
import stations with the following commands:
rake db:import_station["notes/station-data.csv"] 
import bike data with the following commands:
rake db:import_station["notes/bike-data.csv"]
rails db:migrate

This last command will connect you to the database so you can access our site for now:
rails s

Note: If you don’t see pins on the map, then control+C out of rails s and run:
	rails db:seed
	rails s

Functionality:
Our main home page introduces our users to our company and our team. It’s also where a clear outline for how to use our website is!
For new users, simply create an account with us, or returning users can log in with their existing account.
Once you’re logged in, you have complete access to our services! Our navigation bar features a Stations option which lets users view our list of stations, and select a station they would like to rent (unlock) a bike from. On this page, users can also view a list of bikes if they wish, and unlock one after selecting their intended ride time and paying.
Click our header logo, and you’re back home! You can view your profile by clicking on ‘Profile,’ which shows your information on your current profile/account. You can edit your username, password, address, and add money to your account wallet.
Clicking home once again brings you to the main navigation bar, where you can select our map page. This is where you can visualize our stations around you and figure out how to get from one point to another. If the map doesn’t load the first time, you may need to refresh it. Specify where you want to go from, and your destination. The API we use, MapBox, is pretty smart and is able to assume most of the time with a vague address that you mean to be someplace in the Pioneer Valley.
For an example of this, type “Forbes Library” in from and “Cutter house” in to. Or, you can simply select two of our station pins! A route is automatically generated for you with directions and measurements.
Ready to return our bike? Simply click “return,” and you’re all done with your trip!
Oh no, did I hear that your bike wasn’t being returned properly on our end? Click “Report” on our navigation bar to let us know about the issue, and we’ll get back to you.
When you’re done for the day, log out!

Recommended walk-through of features:
Start at sign-in. Create your own account! It can be a dummy account, such as [test2@test.com](mailto:test2@test.com) and password: test123456789.
Logout and log back in if you want to see this working! But it’ll automatically keep you signed in with the account you initially created if you haven’t logged out.
Check out your profile! Want to change something? Try changing your username to something fun, like “pinkfluffyunicorn.”
Next, check out what Western Mass Bikesia stations are around for you to start your journey at by clicking on ‘Map.’ If you’re a student, type the name of your house in and select a destination station!
Pick a bike to use that is docked and available at your selected station.
Rent it! Click payment, select your hours, fill out your payment information, and start riding!
When you’re done, you can let us know by ‘Return’-ing the bike on our website and logging out.
If you want to test out our report form, feel free to fill that out.

Summary of changes since the prototype:
Our newest change has been the map feature, where we can visualize our stations and generate a route between two stations, with instructions and relevant distances laid out on a small part of the screen.
We had a beautiful hovering upgraded navigation bar that was going to go with this page, but we had to scrap it at the last second due to unresolved bugs that we did not have enough time to fix.
We can also now return a bike, and our payment is more elaborate, with additional options including card payment, coupon payment, account wallet, and Paypal. Unfortunately we had to remove Apple Pay. We also can edit user profile information, report issues to the website developers, and read information on our team and company.

**Comment by emmatschu** [comment]
https://github.com/deadroxy/valetbike/pull/153#issuecomment-1530836220

**Comment by emmatschu** [comment]
https://github.com/deadroxy/valetbike/pull/153#issuecomment-1530836220

**Pull request closed without merging**
